[package]
name = "projekt"
version = "0.1.0"
edition = "2024"

[dependencies]
flo_draw = "0.3.1"
flo_canvas = "0.3.1"
futures = "0.3.31"
rand = "0.8"
futures-timer = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
