[package]
name = "lista_3"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
chrono = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"